<form class="caixa-login" method="post" action="/autenticar">
    <h3>Faça seu Login</h3>

    <input type="text" name="email" class="form-control" placeholder="E-mail">

    <input type="password" name="senha" class="form-control" placeholder="Senha">

    <button type="submit" class="botao-login mb-2">Entrar</button><br>


    <?php if ($this->view->login == 'erro') { ?>
        <div class="alert alert-danger mt-2" role="alert">
            *E-mail e ou senha inválido(s)
        </div>


    <?php } ?>
</form>

<a href="/inscreverse" class="text-white">Ainda não possui uma conta? Clique aqui!</a>