<header>
	<nav style="height: 10vh;" class="menu navbar navbar-expand-md navbar-light fixed-top">
		<div class="col-2 d-flex align-items-center ">
			<a href="#home" style="text-decoration: none;">
				<img class="ml-5" src="img/livro-menu-removebg-preview.png" width="80px" alt="">
				<!--<span style="font-size: 25px; text-decoration: none; color: #ee6666d2; font-weight: bold;" class="mx-4 mt-2 ">NOME SITE</span>-->
			</a>
		</div>



		<button class="navbar-toggler bg-danger" data-toggle="collapse" data-target="#nav-principal">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="nav-principal">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<a href="/buscarLivros" class="botao-books nav-nome nav-link  mx-4 text-white ">Livros Disponiveis</a>
				</li>

				<li class="nav-item input-login-adm ">
					<form method="post" action="/autenticarAdm">
						<div class="row">
							<div class="col">
								<input type="text" name="email" class="form-control" placeholder="E-mail">
							</div>
							<div class="col">
								<input type="password" name="senha" class="form-control" placeholder="Senha">
							</div>
							<div class="col-auto">
								<button type="submit" class="btn btn-dark mt-2" onclick="resposta()">Area Adm</button>
							</div>
						</div>

						<? if ($this->view->login == 'erro2') { ?>

							<script>
								function resposta() {

									alert("E-mail e ou senha inválido(s)");

								}
							</script>


						<?  } ?>

					</form>
				</li>


			</ul>

		</div>



	</nav>

</header>



<div id="home" class=" row row-home m-0 p-0 ">

	<div style="height: 100vh;" class="col col-md-6 d-flex  align-items-center justify-content-center">

		<div class=" text-center">


			<form class="caixa-login" method="post" action="/autenticar">
				<h3>Faça seu Login</h3>

				<input type="text" name="email" class="form-control" placeholder="E-mail">

				<input type="password" name="senha" class="form-control" placeholder="Senha">

				<button type="submit" class="botao-login mb-2">Entrar</button><br>


				<?php if ($this->view->login == 'erro') { ?>
					<div class="alert alert-danger mt-2" role="alert">
						*E-mail e ou senha inválido(s)
					</div>


				<?php } ?>
			</form>

			<a href="/inscreverse" class="text-white">Ainda não possui uma conta? Clique aqui!</a>

		</div>


	</div>



	<div style="height: 100vh;" class="col col-md-6 d-flex m-0 p-0 align-items-end justify-content-center">
		<div class=" text-center sombra-img">

			<img src="img/img-home.png" width="580px" alt="">


		</div>

	</div>


</div>









































<!--



<div class="container-fluid h-100">
	<div class="row">
    
    <div class="col-md-6 banner">
    	<div class="row h-100 justify-content-center align-items-center">
    		<div>
				<div class="communicationItem">
					<i class="fas fa-search fa-2x mr-3"></i>
					Siga o que lhe interessa.
				</div>
				<div class="communicationItem">
					<i class="fas fa-user-friends fa-2x mr-3"></i>
					Saiba sobre o que as pessoas estão falando.
				</div>
				<div class="communicationItem">
					<i class="far fa-comment fa-2x mr-3"></i>
					Participe da conversa.
				</div>
			</div>
		</div>
    </div>

    <div class="col-md-6 pt-4 pl-5 pr-5">
		<form method="post" action="/autenticar">
			<div class="row">
				<div class="col">
					<input type="text" name="email" class="form-control" placeholder="E-mail">
				</div>
				<div class="col">
					<input type="password" name="senha" class="form-control" placeholder="Senha">
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-primary mb-2">Entrar</button>
				</div>
			</div>

			<?php //if($this->view->login == 'erro') { 
			?>
				<div class="row">
					<div class="col">
						<span class="text text-danger">*E-mail e ou senha inválido(s)</span>
					</div>
				</div>
			<?php // } 
			?>
		</form>

		<div class="row pt-5 pl-5 pr-5">
			<div class="col pl-5 pr-5">
				<img src="/img/twitter_logo.png" />
				<h1 class="title">Veja o que está acontecendo no mundo agora</h1>

				<h2 class="mt-5 subtitle">Participe hoje do Twitter.</h2>
				<a href="/inscreverse" class="btn btn-primary btn-block mb-2">Inscrever-se</a>
			</div>	
		</div>


    </div>

  </div>
</div>



         <h1>Area do Administrador</h1>
		<form method="post" action="/autenticarAdm">
			<div class="row">
				<div class="col">
					<input type="text" name="email" class="form-control" placeholder="E-mail">
				</div>
				<div class="col">
					<input type="password" name="senha" class="form-control" placeholder="Senha">
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-primary mb-2">Entrar</button>
				</div>
			</div>
            
			<? //if($this->view->login == 'erro2') { 
			?>
			<div class="row">
			  <div class="col">
			  <span class="text text-danger">Acesso negado</span>
			  </div>
			</div>
           <? // } 
			?>

		</form>


    </div>

  </div>
</div>