<script type="text/javascript">
	const bodyElement = document.querySelector('body');
	bodyElement.classList += ' js';
</script>

<header>
	<nav class="menu navbar navbar-expand-md navbar-light fixed-top">
		<div class="container">
			<a href="#home" style="text-decoration: none;">
				<img src="img/livro-menu-removebg-preview.png" width="80px" alt="">
			</a>

			<button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="nav-principal">
				<ul class="navbar-nav ml-auto ">

					<li class="nav-item">
						<a href="/livros" class="nav-link mx-4">Livros</a>
					</li>


					<li class="nav-item">
						<a href="#sobremim" class=" nav-link mx-4">Sobre</a>
					</li>

					<li class="nav-item">
						<a href="#educacao" class=" nav-link mx-4"> Contato</a>
					</li>


					<li class="nav-item">
						<a href="/cadastrar" class="type-button nav-link mx-4"> Entrar</a>
					</li>

				</ul>

			</div>
		</div>

	</nav>

</header>



<main>



	<section id="home" class=" row row-home m-0 p-0 ">

		<div style="height: 100vh;" class="col col-md-6 d-flex  align-items-center justify-content-center">

			<div class="text-center col-text border">


				<h3>Tá afim de doar um livro?</h3>
				<button>Saiba como</button>


			</div>


		</div>

		<div id="img-index" style="height: 100vh;" class="col col-md-6  d-none d-md-block m-0 p-0 align-items-end justify-content-center">

		</div>
	</section>




	<section style="height: 70vh;" id="como-funciona" class="row row-sobre p-0 d-flex  align-items-center justify-content-center text-center">


		<div class="col-12 grid-section categorias d-flex  align-items-center justify-content-center text-center" id="categorias">

			<div class="text-center col-text ">
				<h1 class="titulo">Entenda como Funciona</h1>
				<div class="categorias-lista js-tabmenu button-group ">

					<button class="color">
						1. Faça seu cadastro
					</button>
					<button>
						2. Publique seu livro
					</button>
					<button>
						3. Pronto :)
					</button>

				</div>
				<div class="categorias-descricao js-tabcontent">
					<section>
						<div class="container">
							<div class="row">
								<div class="col-9">
									<h2>primeiro</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

								</div>
								<div class="col-3">
									<img src="img/201-2013472_thats-textbook-icon3-textbook-icon.png" width="150px" alt="">
								</div>
							</div>
						</div>
					</section>

					<section>
						<div class="container">
							<div class="row">
								<div class="col-9">
									<h2>segundo</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>


								</div>
								<div class="col-3">
									<img src="img/201-2013472_thats-textbook-icon3-textbook-icon.png" width="150px" alt="">
								</div>
							</div>
						</div>
					</section>

					<section>
						<div class="container">
							<div class="row">
								<div class="col-9">
									<h2>terceiro</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

								</div>
								<div class="col-3">
									<img src="img/201-2013472_thats-textbook-icon3-textbook-icon.png" width="150px" alt="">
								</div>
							</div>
						</div>
					</section>

				</div>


			</div>



			<script type="text/javascript">
				function initTabNav() {

					const tabMenu = document.querySelectorAll('.js-tabmenu button');
					const tabContent = document.querySelectorAll('.js-tabcontent section');

					if (tabMenu.length && tabContent.length) {

						tabContent[0].classList.add('ativo');

						function activeTab(index) {
							tabContent.forEach((content) => {
								content.classList.remove('ativo');
							});
							tabContent[index].classList.add('ativo');
						}


						tabMenu.forEach((itemMenu, index) => {
							itemMenu.addEventListener('click', () => {
								activeTab(index);
							});
						});

					}
				}
				initTabNav();



				const button = document.querySelectorAll('.js-tabmenu button');
				console.log(button)

				function callback(event) {

					button.forEach((content) => {
						content.classList.remove('color')
					})
					button[event].classList.add('color');

				}


				button.forEach((botao, event) => {
					botao.addEventListener('click', () => {
						callback(event);
					});
				});
			</script>




		</div>



		<div class="col d-flex  align-items-center justify-content-center text-center">


			<a href="/" class="button-sign-up nav-link mx-4">Escreva-se</a>

		</div>


	</section>








	<div style="height: 40%; " id="sobre" class="row row-sobre m-0 p-0 bg-dark">


	</div>

</main>