<div class="container" style="margin-top:10vh;">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">


        <div class="row">
          <div class="col text-center">
            <h1 style="color: #ee6666;">Crie sua conta</h1>
          </div>
        </div>

        <div class="row">
          <div class="col">

            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['nome'] ?>" name="nome" class="form-control" placeholder="Nome">
              </div>

              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['email'] ?>" name="email" class="form-control" placeholder="E-mail">
              </div>

              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['telefone'] ?>" name="telefone" class="form-control" placeholder="Telefone">
              </div>


              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['cidade'] ?>" name="cidade" class="form-control" placeholder="Cidade">
              </div>

              <div class="form-group">
                <input type="password" value="<?= $this->view->usuario['senha'] ?>" name="senha" class="form-control" placeholder="Senha">
              </div>


              <button type="submit" style="background: #ee6666;" class="btn btn-block text-white">Inscrever-se</button>

              <?php if ($this->view->erroCadastro) { ?>

                <div class="alert alert-danger mt-2" role="alert">
                  * Erro ao tentar realizar o cadastro, verifique se todos os campos foram
                  preenchidos corretamente.
                </div>



              <?php } ?>


            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>