<a class="menuItem" href="/sair">
	Sair
</a>


<div class="container text-center">
	<h1>AREA DO ADMINISTRADOR</h1>


	<h3>Usuários Cadastrados</h3>
	<table class="table table-striped table-dark">
		<thead>

			<tr>
				<th scope="col">Usuário</th>
				<th scope="col">Email</th>
				<th scope="col">Telefone</th>
				<th scope="col">Cidade</th>
			</tr>
		</thead>
		<tbody>

		<?php
			foreach ($this->view->info_usuario  as $info_user => $infoUser) {

			?>
				<tr>
					<td><?= $infoUser['nome'] ?></td>
					<td><?= $infoUser['email'] ?></td>
					<td><?= $infoUser['telefone'] ?></td>
					<td><?= $infoUser['cidade'] ?></td>
					<td><a class="btn btn-danger">Remover</a>
				</tr>
			<?php } ?>
		</tbody>
	</table>





</div>