<a class="btn btn-danger mx-5 mt-2" href="/sair">
	Sair
</a>


<div class="container text-center">
	<h1>AREA DO ADMINISTRADOR</h1>


	<h3>Usuários Cadastrados</h3>
	<table class="table table-striped table-dark mb-4">
		<thead>

			<tr>
				<th scope="col">Usuário</th>
				<th scope="col">Email</th>
				<th scope="col">Telefone</th>
				<th scope="col">Cidade</th>
			</tr>
		</thead>
		<tbody>

			<?php
			foreach ($this->view->info_usuario  as $info_user => $infoUser) {

			?>
				<tr>
					<td><?= $infoUser['nome'] ?></td>
					<td><?= $infoUser['email'] ?></td>
					<td><?= $infoUser['telefone'] ?></td>
					<td><?= $infoUser['cidade'] ?></td>
					<td><a class="btn btn-danger text-white">Remover</a>
				</tr>
			<?php } ?>
		</tbody>
	</table>




	<h3>Postagens Realizadas</h3>
	<table class="table table-striped table-dark mb-5">
		<thead>

			<tr>
				<th scope="col">Publicado por: </th>
				<th scope="col">Livro</th>
				<th scope="col">Categoria</th>
				<th scope="col">data</th>
			</tr>
		</thead>
		<tbody>

			<?php
			foreach ($this->view->postagem  as $info_post => $infoPost) {

			?>
				<tr>
					<td><?= $infoPost['nome'] ?></td>
					<td><?= $infoPost['nome_livro'] ?></td>
					<td><?= $infoPost['categoria'] ?></td>
					<td><?= $infoPost['data'] ?></td>
					<td><a class="btn btn-danger">Remover</a>
				</tr>
			<?php } ?>
		</tbody>
	</table>






</div>