<header>
	<nav style="height: 10vh;" class="menu navbar navbar-expand-md navbar-light fixed-top">
		<div class="col-2 d-flex align-items-center ">
			<a href="#home" style="text-decoration: none;">
				<img class="ml-5" src="img/livro-menu-removebg-preview.png" width="80px" alt="">
				<!--<span style="font-size: 25px; text-decoration: none; color: #ee6666d2; font-weight: bold;" class="mx-4 mt-2 ">NOME SITE</span>-->
			</a>
		</div>



		<button class="navbar-toggler bg-danger" data-toggle="collapse" data-target="#nav-principal">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="nav-principal">
			<ul class="navbar-nav ml-auto">

				<li class="nav-item">
					<a href="/perfil" class="botao-books nav-nome nav-link  mx-4 text-white ">Perfil</a>
				</li>


				<li class="nav-item">
					<a href="/buscarLivros" class="botao-books nav-nome nav-link  mx-4 text-white ">Buscar Livros</a>
				</li>


				<li class="nav-item">
					<a href="/sair" class=" nav-nome nav-link  mx-4 text-white ">Sair</a>
				</li>

			</ul>

		</div>



	</nav>

</header>








<div id="projetos" class=" row  bg-white m-0 p-0">


	<div class="col text-center">


		<h1 style="margin-top: 15vh; color:#ee6666;">Todos os Livros Disponíveis</h1>

		<div class="row">



			<?php
			foreach ($this->view->livrostodos as $id_postagem => $postagens) {

			?>


				<div class="col-3 mb-5 d-flex align-items-center justify-content-center text-center">

					<div class=" card d-flex align-items-center justify-content-center" style="width: 15rem; height:auto;">
						<img style=" height:35vh; width:200px;" class="card-img-top pt-3" src="<?= $postagens['imagem'] ?>" alt="Card image cap">
						<div class="card-body">
							<h5 class="card-title"><?= $postagens['nome_livro'] ?></h5>
						</div>
						<ul class="list-group list-group-flush">

							<li class="list-group-item">Cidade: <?= $postagens['cidade'] ?> </li>
							<li class="list-group-item"> Data da publicação: <?= $postagens['data'] ?> </li>

						</ul>



					</div>
				</div>




			<?php
			} ?>



		</div>


	</div>


</div>