<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome">Nome do Usuário</span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">






			<form action="/livros" method="post">
              <h3 class="title-publi-book">Publicar Livro</h3>
              <div class=" form-group d-flex align-items-center justify-content-center">
                <input class="form-control" name="imagem" type="text" placeholder="Informe a Url da imagem">
              </div>

              <div class="form-group d-flex align-items-center justify-content-center">
                <input class="form-control" name="nome_livro" type="text" placeholder="Informe o nome do livro">
              </div>

              <div class="form-group d-flex align-items-center justify-content-center">

                <select name="categoria" size="5">
                  <option value="categoria" disabled selected>Selecione a Categoria</option>
                  <option value="Autoajuda">Autoajuda</option>
                  <option value="Aventura">Aventura</option>
                  <option value="Biográfia">Biográfia</option>
                  <option value="Comédia">Comédia</option>
                  <option value="Didático">Didático</option>
                  <option value="Drama">Drama</option>
                  <option value="Fantasia">Fantasia</option>
                  <option value="Ficção científica">Ficção científica</option>
                  <option value="História em Quadrinhos">História em Quadrinhos</option>
                  <option value="Infantil">Infantil</option>
                  <option value="Infanto Juvenil">Infanto Juvenil</option>
                  <option value="Poesia">Poesia</option>
                  <option value="Romance">Romance</option>
                  <option value="Terror">Terror</option>
                  <option value="Outro">Outro</option>
                </select>

              </div>

			  <button type="submit" class="btn btn-primary">Publicar</button>
            </form>


               <!--
					<form>
						<textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>  -->








				</div>
			</div>


















			<div class="row tweet">
				<div class="col">
					<p><strong>Nome do Usuário</strong> <span class="text text-muted">- data tweet</span></p>
					<p>Conteúdo do tweet</p>

					<br />
					<form>
						<div class="col d-flex justify-content-end">
							<button type="submit" class="btn btn-danger"><small>Remover</small></button>
						</div>
					</form>
				</div>
			</div>

			<div class="row tweet">
				<div class="col">
					<p><strong>Nome do Usuário</strong> <span class="text text-muted">- data tweet</span></p>
					<p>Conteúdo do tweet</p>

					<br />
					<form>
						<div class="col d-flex justify-content-end">
							<button type="submit" class="btn btn-danger"><small>Remover</small></button>
						</div>
					</form>		
				</div>
			</div>


		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="#" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>