<header>
	<nav style="height: 10vh;" class="menu navbar navbar-expand-md navbar-light fixed-top">
		<div class="col-2 d-flex align-items-center ">
			<a href="#home" style="text-decoration: none;">
				<img class="ml-5" src="img/livro-menu-removebg-preview.png" width="80px" alt="">
				<!--<span style="font-size: 25px; text-decoration: none; color: #ee6666d2; font-weight: bold;" class="mx-4 mt-2 ">NOME SITE</span>-->
			</a>
		</div>



		<button class="navbar-toggler bg-danger" data-toggle="collapse" data-target="#nav-principal">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="nav-principal">
			<ul class="navbar-nav ml-auto">


				<li class="nav-item">
					<a href="/" class=" nav-nome nav-link  mx-4 text-white ">Voltar</a>
				</li>

			</ul>

		</div>



	</nav>

</header>



<div class="row row-books m-0 p-0  d-flex align-items-center justify-content-center text-center">

	<div class="container">
		<div class="col col-books text-center">
			<h1 class="mt-5">Livros Disponíveis</h1>
			<div class="row">
				<?php

				foreach ($this->view->livrostodos as $id_postagem => $postagens) {

				?>
					<div class="col-3  d-flex align-items-center justify-content-center text-center">
						<div class="card d-flex align-items-center justify-content-center">
							<a href="/inscreverse"><img class="card-img-top " src="<?= $postagens['imagem'] ?>" alt="livro + <?= $postagens['nome_livro'] ?>"></a>
							<div class="card-body">
								<h3 class="card-title"><?= $postagens['nome_livro'] ?></h3>
							</div>
							<ul class="list-group list-group-flush">

								<li class="list-group-item">Cidade: <?= $postagens['cidade'] ?> </li>

							</ul>
						</div>
					</div>
				<?php

				} ?>


			</div>
		</div>
		<!---<a href="/inscreverse">Veja mais</a>-->
	</div>


</div>