<header>
	<nav style="height: 10vh;" class="menu navbar navbar-expand-md navbar-light fixed-top">
		<div class="col-2 d-flex align-items-center ">
			<a href="#home" style="text-decoration: none;">
				<img class="ml-5" src="img/livro-menu-removebg-preview.png" width="80px" alt="">
				<!--<span style="font-size: 25px; text-decoration: none; color: #ee6666d2; font-weight: bold;" class="mx-4 mt-2 ">NOME SITE</span>-->
			</a>
		</div>



		<button class="navbar-toggler bg-danger" data-toggle="collapse" data-target="#nav-principal">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="nav-principal">
			<ul class="navbar-nav ml-auto">



				<li class="nav-item">
					<a href="/buscarLivros" class="botao-books nav-nome nav-link  mx-4 text-white ">Buscar Livros</a>
				</li>


				<li class="nav-item">
					<a href="/sair" class=" nav-nome nav-link  mx-4 text-white ">Sair</a>
				</li>

			</ul>

		</div>



	</nav>

</header>





<div style="height: 50vh;" class="row area-home p-0 m-0 ">
	<div class="sombra-home d-flex align-items-center justify-content-start">
		<div class=" col-4">

			<div class="text-center area-info-home ">
				<h1 class="title-home">Olá, <?php echo $_SESSION['nome'] ?> !</h1>

				<p class="frase-home text-justify">
					Aqui é sua area pessoal, onde você poderá ver os livros disponíveis e doar.
				</p>


			</div>

		</div>
	</div>

</div>




<div style="height: 75vh;" class="row p-0 m-0">

	<div class=" col-6 d-flex align-items-center justify-content-center">



		<?php
		foreach ($this->view->info_usuario  as $info_user => $infoUser) {

		?>



			<div style="width: 35vw;" class="area-info-home2 p-5">

				<h4 class="text-danger">Dados do Perfil</h4>
				<h5><span>Nome:</span> <?= $infoUser['nome'] ?></h5>
				<h5><span>Email:</span> <?= $infoUser['email'] ?></h5>
				<h5><span>Telefone:</span> <?= $infoUser['telefone'] ?></h5>
				<h5 class="mb-3"><span>Cidade:</span> <?= $infoUser['cidade'] ?></h5>

			<?php } ?>

			<button class="btn btn-danger mr-3">Editar Perfil</button>
			<button class="btn btn-danger">Excluir Conta</button>


			<h4 class="projetos-nome  text-center" style="color:#757575; font-size:20px;margin-top:20px">Livros doados por você: </h4>

			<h5 class="text-center mb-2"> <?= $this->view->total_livros['total_livros'] ?> livro(s) doado(s)</h5>



			</div>



	</div>











	<div class=" col d-flex caixa-publicacao align-items-center justify-content-start">

		<form action="/postagens" method="post">

			<div style="width: 40vw;" class="area-publi-home p-5">
				<h3 class="title-publi-book">Publicar Livro</h3>
				<div class=" form-group d-flex align-items-center justify-content-center">


					<input class="form-control" name="imagem" type="text" placeholder="Informe a Url da imagem">
				</div>

				<div class="form-group d-flex align-items-center justify-content-center">
					<input class="form-control" name="nome_livro" type="text" placeholder="Informe o nome do livro">
				</div>

				<div class="form-group d-flex align-items-center justify-content-center">

					<select name="categoria" size="5">
						<option value="categoria" disabled selected>Selecione a Categoria</option>
						<option value="Autoajuda">Autoajuda</option>
						<option value="Aventura">Aventura</option>
						<option value="Biográfia">Biográfia</option>
						<option value="Comédia">Comédia</option>
						<option value="Didático">Didático</option>
						<option value="Drama">Drama</option>
						<option value="Fantasia">Fantasia</option>
						<option value="Ficção científica">Ficção científica</option>
						<option value="História em Quadrinhos">História em Quadrinhos</option>
						<option value="Infantil">Infantil</option>
						<option value="Infanto Juvenil">Infanto Juvenil</option>
						<option value="Poesia">Poesia</option>
						<option value="Romance">Romance</option>
						<option value="Terror">Terror</option>
						<option value="Outro">Outro</option>
					</select>

				</div>


				<button type="submit" class="btn btn-danger">Publicar</button>

				<?php if ($this->view->post == 'erro') { ?>

					<div class="alert alert-danger mt-2" role="alert">
						* Erro ao tentar publicar o livro, verifique se todos os campos foram
						preenchidos corretamente.
					</div>

				<?php } ?>


			</div>
		</form>


	</div>



</div>
<!--FIM COL-->





<h1 class="projetos-nome text-center mt-5 pt-5" style="color:#757575;">Meus Livros Publicados</h1>

<h5 class="text-center mb-5"> <?= $this->view->total_livros['total_livros'] ?> livro(s) doado(s) por você</h5>

<div class="container">

	<div id="projetos" class=" row  bg-white m-0 p-0">


		<div class="col">

			<div class="row">



				<?php
				foreach ($this->view->postagem as $id_postagem => $postagens) {

				?>


					<div class="col-3 mb-5 d-flex align-items-center justify-content-center text-center">

						<div class=" card d-flex align-items-center justify-content-center" style="width: 15rem; height:auto;">
							<img style=" height:35vh; width:200px;" class="card-img-top pt-3" src="<?= $postagens['imagem'] ?>" alt="Card image cap">
							<div class="card-body">
								<h5 class="card-title"><?= $postagens['nome_livro'] ?></h5>
							</div>
							<ul class="list-group list-group-flush">




							</ul>

							<a class="btn btn-danger m-2 text-white" href="/remover_postagens?remover_postagens=remover&id=<?= $postagens['id'] ?>">Remover</a>

							<a class="btn btn-secondary m-2 px-4 text-white">Editar</a>

						</div>
					</div>




				<?php
				} ?>



			</div>


		</div>


	</div>


</div>